import { useState } from "react";
import { motion } from "motion/react";
import { GraduationCap, Download, Copy, Check, FileText, Sparkles } from "lucide-react";
import { toast } from "sonner";

const mockPaper = {
  title: "The Evolution and Impact of Machine Learning in Modern Computing",
  authors: "Generated by StudyForge AI",
  date: "March 23, 2026",
  abstract:
    "This paper explores the fundamental concepts, methodologies, and applications of machine learning in contemporary computing systems. We examine the three primary paradigms of machine learning—supervised, unsupervised, and reinforcement learning—and analyze their respective contributions to solving complex computational problems. Through a comprehensive review of current literature and practical implementations, we demonstrate how machine learning algorithms have revolutionized data processing, pattern recognition, and predictive analytics across various domains.",
  sections: [
    {
      title: "1. Introduction",
      content:
        "Machine learning represents a paradigm shift in how computers process and learn from data. Unlike traditional programming approaches where explicit instructions are provided, machine learning systems develop their own understanding through exposure to data and experience. This capability has enabled unprecedented advances in fields ranging from computer vision to natural language processing, fundamentally transforming how we interact with technology.",
    },
    {
      title: "2. Methodology",
      content:
        "Our research methodology encompasses a systematic review of machine learning algorithms and their applications. We categorize learning approaches into three primary types: supervised learning, which utilizes labeled training data; unsupervised learning, which identifies patterns in unlabeled data; and reinforcement learning, which optimizes decision-making through reward-based feedback. Each approach is evaluated based on computational efficiency, accuracy, and practical applicability.",
    },
    {
      title: "3. Key Algorithms and Techniques",
      content:
        "Several fundamental algorithms form the foundation of modern machine learning. Linear regression and logistic regression provide baseline statistical approaches for prediction tasks. Decision trees and random forests offer interpretable models for classification problems. Neural networks, particularly deep learning architectures, have achieved breakthrough performance in complex tasks such as image recognition and language translation. Support vector machines provide robust classification in high-dimensional spaces, while clustering algorithms like K-means enable unsupervised pattern discovery.",
    },
    {
      title: "4. Applications and Impact",
      content:
        "Machine learning applications span diverse domains. In healthcare, predictive models assist in disease diagnosis and treatment planning. Financial institutions employ machine learning for fraud detection and risk assessment. Autonomous vehicles rely on computer vision and reinforcement learning for navigation. Natural language processing powers virtual assistants and translation services. Recommendation systems enhance user experience in e-commerce and entertainment platforms. These applications demonstrate the transformative potential of machine learning across industries.",
    },
    {
      title: "5. Challenges and Considerations",
      content:
        "Despite significant progress, machine learning faces several challenges. Overfitting occurs when models learn training data too specifically, failing to generalize to new examples. Data quality and quantity significantly impact model performance, creating barriers in domains with limited labeled data. Computational requirements for training complex models demand substantial resources. Interpretability remains a concern, particularly in critical applications where understanding decision-making processes is essential. Ethical considerations regarding bias, privacy, and accountability require ongoing attention.",
    },
    {
      title: "6. Conclusion",
      content:
        "Machine learning has emerged as a cornerstone technology in modern computing, enabling systems to learn from experience and adapt to new challenges. The three primary learning paradigms—supervised, unsupervised, and reinforcement learning—each contribute unique capabilities to solving complex problems. As algorithms continue to evolve and computational resources expand, machine learning will increasingly shape how we approach data analysis, automation, and intelligent decision-making. Future research should address current limitations while exploring novel applications and ethical frameworks to ensure responsible development and deployment of machine learning systems.",
    },
  ],
  references: [
    "Bishop, C. M. (2006). Pattern Recognition and Machine Learning. Springer.",
    "Goodfellow, I., Bengio, Y., & Courville, A. (2016). Deep Learning. MIT Press.",
    "Mitchell, T. M. (1997). Machine Learning. McGraw-Hill.",
    "Russell, S., & Norvig, P. (2020). Artificial Intelligence: A Modern Approach. Pearson.",
  ],
};

export function ResearchPaperPage() {
  const [copied, setCopied] = useState(false);
  const [topic, setTopic] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);
  const [showPaper, setShowPaper] = useState(true);

  const handleGenerate = () => {
    if (!topic.trim()) {
      toast.error("Please enter a research topic");
      return;
    }
    setIsGenerating(true);
    setTimeout(() => {
      setIsGenerating(false);
      setShowPaper(true);
      toast.success("Research paper generated successfully!");
    }, 2000);
  };

  const handleCopy = () => {
    const text = `${mockPaper.title}\n${mockPaper.authors}\n${mockPaper.date}\n\nAbstract\n${mockPaper.abstract}\n\n${mockPaper.sections
      .map((section) => `${section.title}\n${section.content}`)
      .join("\n\n")}\n\nReferences\n${mockPaper.references.join("\n")}`;
    navigator.clipboard.writeText(text);
    setCopied(true);
    toast.success("Paper copied to clipboard!");
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    toast.success("Paper downloaded as PDF!");
  };

  return (
    <div className="max-w-5xl mx-auto">
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
      >
        {/* Header */}
        <div className="mb-8 flex items-start justify-between">
          <div>
            <div className="flex items-center gap-3 mb-2">
              <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-[#6366f1]/20 to-[#3b82f6]/20 flex items-center justify-center">
                <GraduationCap className="w-5 h-5 text-[#6366f1]" />
              </div>
              <h1 className="text-4xl font-bold bg-gradient-to-r from-[#6366f1] to-[#3b82f6] bg-clip-text text-transparent">
                Research Paper Generator
              </h1>
            </div>
            <p className="text-muted-foreground text-lg ml-[52px]">
              AI-powered academic paper generation
            </p>
          </div>

          {showPaper && (
            <div className="flex gap-2">
              <button
                onClick={handleCopy}
                className="p-3 rounded-xl bg-card/80 border border-border/50 hover:bg-accent transition-all duration-200"
              >
                {copied ? <Check className="w-5 h-5 text-green-500" /> : <Copy className="w-5 h-5" />}
              </button>
              <button
                onClick={handleDownload}
                className="p-3 rounded-xl bg-gradient-to-r from-[#6366f1] to-[#3b82f6] text-white hover:shadow-lg hover:shadow-[#6366f1]/20 transition-all duration-200"
              >
                <Download className="w-5 h-5" />
              </button>
            </div>
          )}
        </div>

        {/* Input Area */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.1 }}
          className="p-6 rounded-2xl bg-card/80 border border-border/50 backdrop-blur-sm mb-8"
        >
          <label className="block text-sm font-medium mb-3">Research Topic</label>
          <div className="flex gap-3">
            <input
              type="text"
              value={topic}
              onChange={(e) => setTopic(e.target.value)}
              placeholder="Enter your research topic (e.g., Machine Learning Applications)"
              className="flex-1 px-4 py-3 bg-background/50 border border-border/50 rounded-xl focus:outline-none focus:ring-2 focus:ring-[#6366f1]/50 transition-all"
            />
            <button
              onClick={handleGenerate}
              disabled={isGenerating}
              className="px-6 py-3 rounded-xl bg-gradient-to-r from-[#6366f1] to-[#3b82f6] text-white font-semibold hover:shadow-lg hover:shadow-[#6366f1]/20 transition-all duration-200 disabled:opacity-50 flex items-center gap-2"
            >
              {isGenerating ? (
                <>
                  <motion.div
                    animate={{ rotate: 360 }}
                    transition={{ duration: 1, repeat: Infinity, ease: "linear" }}
                  >
                    <Sparkles className="w-5 h-5" />
                  </motion.div>
                  Generating...
                </>
              ) : (
                <>
                  <Sparkles className="w-5 h-5" />
                  Generate
                </>
              )}
            </button>
          </div>
        </motion.div>

        {/* Research Paper */}
        {showPaper && (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.2 }}
            className="p-12 rounded-2xl bg-white text-gray-900 shadow-2xl"
          >
            {/* Title Page */}
            <div className="text-center mb-12 pb-12 border-b-2 border-gray-200">
              <h1 className="text-3xl font-bold mb-6">{mockPaper.title}</h1>
              <p className="text-lg mb-2">{mockPaper.authors}</p>
              <p className="text-gray-600">{mockPaper.date}</p>
            </div>

            {/* Abstract */}
            <div className="mb-12">
              <h2 className="text-2xl font-bold mb-4 text-center">Abstract</h2>
              <p className="text-justify leading-relaxed text-gray-700">{mockPaper.abstract}</p>
            </div>

            {/* Sections */}
            <div className="space-y-8">
              {mockPaper.sections.map((section, index) => (
                <motion.div
                  key={index}
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: 0.3 + index * 0.1 }}
                >
                  <h2 className="text-xl font-bold mb-4">{section.title}</h2>
                  <p className="text-justify leading-relaxed text-gray-700">{section.content}</p>
                </motion.div>
              ))}
            </div>

            {/* References */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 1 }}
              className="mt-12 pt-8 border-t-2 border-gray-200"
            >
              <h2 className="text-2xl font-bold mb-4">References</h2>
              <ol className="space-y-2">
                {mockPaper.references.map((ref, index) => (
                  <li key={index} className="text-gray-700">
                    {index + 1}. {ref}
                  </li>
                ))}
              </ol>
            </motion.div>
          </motion.div>
        )}

        {/* Export Options */}
        {showPaper && (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 1.2 }}
            className="mt-8 grid grid-cols-1 md:grid-cols-2 gap-6"
          >
            <button
              onClick={handleDownload}
              className="p-6 rounded-2xl bg-card/80 border border-border/50 hover:border-[#6366f1]/50 transition-all duration-200 text-left group"
            >
              <div className="flex items-center gap-4">
                <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-[#6366f1]/20 to-[#3b82f6]/20 flex items-center justify-center group-hover:scale-110 transition-transform duration-200">
                  <FileText className="w-6 h-6 text-[#6366f1]" />
                </div>
                <div>
                  <h4 className="font-semibold mb-1">Export as PDF</h4>
                  <p className="text-sm text-muted-foreground">Download in PDF format</p>
                </div>
              </div>
            </button>

            <button
              onClick={handleDownload}
              className="p-6 rounded-2xl bg-card/80 border border-border/50 hover:border-[#6366f1]/50 transition-all duration-200 text-left group"
            >
              <div className="flex items-center gap-4">
                <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-[#6366f1]/20 to-[#3b82f6]/20 flex items-center justify-center group-hover:scale-110 transition-transform duration-200">
                  <FileText className="w-6 h-6 text-[#6366f1]" />
                </div>
                <div>
                  <h4 className="font-semibold mb-1">Export as DOCX</h4>
                  <p className="text-sm text-muted-foreground">Download in Word format</p>
                </div>
              </div>
            </button>
          </motion.div>
        )}
      </motion.div>
    </div>
  );
}
