import { useEffect, useMemo, useState } from "react";
import { useLocation } from "react-router";
import {
  completeDay,
  generateStudyPlan,
  getMyReports,
  getMyStudyPlan,
  type StudyDay,
  type StudyPlan,
} from "../api/aiApi";
import { loadReportFromSession } from "../app/lib/session";

const parseDateInput = (value: string | Date) => {
  if (value instanceof Date) return value;

  const raw = String(value || "");
  if (/^\d{4}-\d{2}-\d{2}$/.test(raw)) {
    const [y, m, d] = raw.split("-").map(Number);
    return new Date(y, m - 1, d);
  }

  return new Date(raw);
};

const formatDayDate = (value: string) => {
  const date = parseDateInput(value);
  const dd = String(date.getDate()).padStart(2, "0");
  const mm = String(date.getMonth() + 1).padStart(2, "0");
  const yyyy = date.getFullYear();
  return `${dd}/${mm}/${yyyy}`;
};

const toYmd = (value: string | Date) => {
  const date = parseDateInput(value);
  const yyyy = date.getFullYear();
  const mm = String(date.getMonth() + 1).padStart(2, "0");
  const dd = String(date.getDate()).padStart(2, "0");
  return `${yyyy}-${mm}-${dd}`;
};

export default function StudyPlanPage() {
  const [plan, setPlan] = useState<StudyPlan | null>(null);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [examDate, setExamDate] = useState("");
  const [reportId, setReportId] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [successMessage, setSuccessMessage] = useState<string | null>(null);
  const [selectedDay, setSelectedDay] = useState<StudyDay | null>(null);

  const location = useLocation();

  useEffect(() => {
    const resolveReportId = async () => {
      const params = new URLSearchParams(location.search);
      const fromQuery = params.get("reportId");
      const fromSession = loadReportFromSession()?._id;
      const fromLocal = localStorage.getItem("latestReportId") || "";
      const initial = fromQuery || fromSession || fromLocal;

      if (initial) {
        setReportId(initial);
        return;
      }

      try {
        const reports = await getMyReports();
        const latest = reports[0]?._id || "";
        if (latest) {
          localStorage.setItem("latestReportId", latest);
          setReportId(latest);
        }
      } catch {
        // ignore here, generation path will show actionable error
      }
    };

    resolveReportId();
  }, [location.search]);

  useEffect(() => {
    const loadPlan = async () => {
      try {
        setLoading(true);
        setError(null);
        const result = await getMyStudyPlan();
        setPlan(result.plan);
      } catch (err) {
        setError(err instanceof Error ? err.message : "Failed to load study plan");
      } finally {
        setLoading(false);
      }
    };

    loadPlan();
  }, []);

  const today = useMemo(() => toYmd(new Date()), []);

  const completedDays = useMemo(() => plan?.days.filter((d) => d.completed).length || 0, [plan]);
  const totalDays = useMemo(() => plan?.days.length || 0, [plan]);
  const progress = totalDays ? Math.round((completedDays / totalDays) * 100) : 0;

  const generatePlanNow = async () => {
    if (!reportId) {
      setError("No report found. Generate a report first, then create a study plan.");
      return;
    }

    if (!examDate) {
      setError("Please select an exam date.");
      return;
    }

    try {
      setGenerating(true);
      setError(null);
      const result = await generateStudyPlan(reportId, examDate);
      setPlan(result.plan);
      setSuccessMessage("Study plan generated successfully!");
      setTimeout(() => setSuccessMessage(null), 2500);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to generate study plan");
    } finally {
      setGenerating(false);
    }
  };

  const markComplete = async (day: StudyDay) => {
    if (!plan) return;

    try {
      setError(null);
      setSelectedDay(day);
      const result = await completeDay(plan._id, day.day);
      setPlan(result.plan);
      setSuccessMessage(result.message);
      setTimeout(() => setSuccessMessage(null), 2500);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to mark day complete");
    } finally {
      setSelectedDay(null);
    }
  };

  return (
    <div className="min-h-full bg-[#0f172a] p-6 text-white">
      <div className="mx-auto max-w-6xl space-y-6">
        <div>
          <h1 className="text-2xl font-bold">📅 Your Study Plan</h1>
          <div className="mt-2 flex items-center gap-2 text-sm text-slate-400">
            <span>Generated by Nemotron via NVIDIA NIM</span>
            <span className="rounded-full bg-purple-900 px-2 py-0.5 text-xs text-purple-300">AI Structured Output</span>
          </div>
        </div>

        {loading && (
          <div className="flex justify-center rounded-xl border border-slate-700 bg-[#1e293b] p-12">
            <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-indigo-500" />
          </div>
        )}

        {!loading && successMessage && (
          <div className="rounded-xl border border-green-600 bg-green-950/40 p-3 text-green-200">{successMessage}</div>
        )}

        {!loading && error && <div className="rounded-xl border border-red-600 bg-red-950/40 p-3 text-red-200">{error}</div>}

        {!loading && !plan && (
          <div className="mx-auto max-w-lg rounded-xl border border-slate-700 bg-[#1e293b] p-8 text-center">
            <div className="text-5xl">📅</div>
            <h2 className="mt-4 text-xl font-semibold text-white">Create Your Personalized Study Plan</h2>
            <p className="mt-2 text-sm text-slate-400">
              Tell us your exam date and we'll build a day-by-day plan based on your quiz results
            </p>

            <div className="mt-6 space-y-3">
              <input
                type="date"
                min={today}
                value={examDate}
                onChange={(e) => setExamDate(e.target.value)}
                className="w-full rounded-xl border border-slate-600 bg-slate-900 p-3 text-white"
              />

              <button
                type="button"
                onClick={generatePlanNow}
                disabled={generating || !examDate}
                className="w-full rounded-xl bg-indigo-600 px-6 py-3 font-semibold text-white transition-all duration-200 hover:bg-indigo-700 disabled:cursor-not-allowed disabled:opacity-60"
              >
                {generating ? (
                  <span className="inline-flex items-center gap-2">
                    <span className="animate-spin rounded-full h-8 w-8 border-b-2 border-indigo-500" />
                    Generating with NVIDIA Nemotron...
                  </span>
                ) : (
                  "Generate My Study Plan 🚀"
                )}
              </button>
            </div>
          </div>
        )}

        {!loading && plan && (
          <>
            <div className="grid grid-cols-1 gap-4 md:grid-cols-4">
              <div className="rounded-xl bg-[#1e293b] p-4">
                <p className="text-sm text-slate-400">📅 Total Days</p>
                <p className="mt-1 text-2xl font-bold">{plan.totalDays}</p>
              </div>
              <div className="rounded-xl bg-[#1e293b] p-4">
                <p className="text-sm text-slate-400">✅ Completed</p>
                <p className="mt-1 text-2xl font-bold">{completedDays}</p>
              </div>
              <div className="rounded-xl bg-[#1e293b] p-4">
                <p className="text-sm text-slate-400">📚 Study Days</p>
                <p className="mt-1 text-2xl font-bold">{plan.days.filter((d) => d.type === "study").length}</p>
              </div>
              <div className="rounded-xl bg-[#1e293b] p-4">
                <p className="text-sm text-slate-400">🧘 Rest Days</p>
                <p className="mt-1 text-2xl font-bold">{plan.days.filter((d) => d.type === "rest").length}</p>
              </div>
            </div>

            <div className="rounded-xl bg-[#1e293b] p-4">
              <div className="mb-2 flex items-center justify-between text-sm text-slate-300">
                <span>Overall Progress</span>
                <span>{progress}%</span>
              </div>
              <div className="h-3 rounded-full bg-slate-700">
                <div className="h-3 rounded-full bg-indigo-500" style={{ width: `${progress}%` }} />
              </div>
              <p className="mt-2 text-xs italic text-slate-500">Generated via: {plan.generatedVia}</p>
            </div>

            <h2 className="text-lg font-semibold text-white">Your Day-by-Day Plan</h2>

            <div className="max-h-[560px] space-y-3 overflow-y-auto pr-1">
              {plan.days.map((day) => {
                const dateKey = toYmd(day.date);
                const isToday = dateKey === today;
                const isCompleting = !!selectedDay && selectedDay.day === day.day;

                const typeStyles =
                  day.type === "study"
                    ? "border-indigo-500 bg-slate-800"
                    : day.type === "review"
                      ? "border-yellow-500 bg-slate-800"
                      : "border-green-500 bg-slate-700";

                const badgeStyles =
                  day.type === "study"
                    ? "bg-indigo-900 text-indigo-300"
                    : day.type === "review"
                      ? "bg-yellow-900 text-yellow-300"
                      : "bg-green-900 text-green-300";

                return (
                  <div
                    key={`day-${day.day}`}
                    className={`relative rounded-xl border-l-4 ${typeStyles} p-4 ${day.completed ? "opacity-60" : ""}`}
                    onClick={() => setSelectedDay(day)}
                  >
                    {day.completed && <div className="absolute right-3 top-3 text-green-400">✅</div>}

                    <div className="grid grid-cols-1 gap-4 md:grid-cols-[180px_1fr_160px]">
                      <div>
                        <p className="text-lg font-bold text-indigo-400">Day {day.day}</p>
                        <p className="text-sm text-slate-400">{formatDayDate(day.date)}</p>
                        <span className={`mt-2 inline-block rounded-full px-2 py-0.5 text-xs ${badgeStyles}`}>{day.type}</span>
                      </div>

                      <div>
                        <p className="font-medium text-white">{day.topic}</p>
                        <p className="mt-1 text-sm italic text-slate-300">{day.goal}</p>
                        <ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-slate-400">
                          {day.tasks.map((task, idx) => (
                            <li key={`${day.day}-task-${idx}`}>{task}</li>
                          ))}
                        </ul>
                        <p className="mt-2 text-xs text-slate-500">⏱️ Est. {day.estimatedHours}h</p>
                      </div>

                      <div className="flex flex-col items-start justify-start gap-2 md:items-end">
                        {day.completed ? (
                          <span className="text-sm text-green-400">✅ Done</span>
                        ) : (
                          <>
                            {isToday && <span className="rounded-full bg-indigo-900 px-2 py-0.5 text-xs text-indigo-300">📌 Today</span>}
                            {day.type !== "rest" && (
                              <button
                                type="button"
                                onClick={() => markComplete(day)}
                                disabled={isCompleting}
                                className="rounded-lg bg-slate-700 px-3 py-1.5 text-sm text-slate-300 transition-all duration-200 hover:bg-indigo-600 hover:text-white disabled:opacity-60"
                              >
                                {isCompleting ? "Saving..." : "Mark Complete"}
                              </button>
                            )}
                          </>
                        )}
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>

            <button
              type="button"
              onClick={() => {
                setPlan(null);
                setError(null);
                setSuccessMessage(null);
              }}
              className="text-sm text-slate-400 transition-all duration-200 hover:text-white"
            >
              Regenerate Plan
            </button>
          </>
        )}
      </div>
    </div>
  );
}
